#include"piece.hpp"

std::unordered_map<int, std::string> PieceToStr = {
    { PAWN,   "•à" },
    { LANCE,  "" },
    { KNIGHT, "Œj" },
    { SILVER, "‹â" },
    { GOLD,   "‹à" },
    { BISHOP, "Šp" },
    { ROOK,   "”ò" },
    { BLACK_PAWN,    "æŽè•à" },
    { BLACK_LANCE,   "æŽè" },
    { BLACK_KNIGHT,  "æŽèŒj" },
    { BLACK_SILVER,  "æŽè‹â" },
    { BLACK_GOLD,    "æŽè‹à" },
    { BLACK_BISHOP,  "æŽèŠp" },
    { BLACK_ROOK,    "æŽè”òŽÔ" },
    { BLACK_KING,    "æŽè‹Ê" },
    { BLACK_PAWN_PROMOTE,   "æŽè‚Æ" },
    { BLACK_LANCE_PROMOTE,  "æŽè¬" },
    { BLACK_KNIGHT_PROMOTE, "æŽè¬Œj" },
    { BLACK_SILVER_PROMOTE, "æŽè¬‹â" },
    { BLACK_BISHOP_PROMOTE, "æŽè”n" },
    { BLACK_ROOK_PROMOTE,   "æŽè—³" },
    { WHITE_PAWN,    "ŒãŽè•à" },
    { WHITE_LANCE,   "ŒãŽè" },
    { WHITE_KNIGHT,  "ŒãŽèŒj" },
    { WHITE_SILVER,  "ŒãŽè‹â" },
    { WHITE_GOLD,    "ŒãŽè‹à" },
    { WHITE_BISHOP,  "ŒãŽèŠp" },
    { WHITE_ROOK,    "ŒãŽè”òŽÔ" },
    { WHITE_KING,    "ŒãŽè‹Ê" },
    { WHITE_PAWN_PROMOTE,   "ŒãŽè‚Æ" },
    { WHITE_LANCE_PROMOTE,  "ŒãŽè¬" },
    { WHITE_KNIGHT_PROMOTE, "ŒãŽè¬Œj" },
    { WHITE_SILVER_PROMOTE, "ŒãŽè¬‹â" },
    { WHITE_BISHOP_PROMOTE, "ŒãŽè”n" },
    { WHITE_ROOK_PROMOTE,   "ŒãŽè—³" },
};

std::unordered_map<int, std::string> PieceToSfenStr = {
    { EMPTY,  "  " },
    { PAWN,   "P" },
    { LANCE,  "L" },
    { KNIGHT, "N" },
    { SILVER, "S" },
    { GOLD,   "G" },
    { BISHOP, "B" },
    { ROOK,   "R" },
    { BLACK_PAWN,    " P" },
    { BLACK_LANCE,   " L" },
    { BLACK_KNIGHT,  " N" },
    { BLACK_SILVER,  " S" },
    { BLACK_GOLD,    " G" },
    { BLACK_BISHOP,  " B" },
    { BLACK_ROOK,    " R" },
    { BLACK_KING,    " K" },
    { BLACK_PAWN_PROMOTE,   "+P" },
    { BLACK_LANCE_PROMOTE,  "+L" },
    { BLACK_KNIGHT_PROMOTE, "+N" },
    { BLACK_SILVER_PROMOTE, "+S" },
    { BLACK_BISHOP_PROMOTE, "+B" },
    { BLACK_ROOK_PROMOTE,   "+R" },
    { WHITE_PAWN,    " p" },
    { WHITE_LANCE,   " l" },
    { WHITE_KNIGHT,  " n" },
    { WHITE_SILVER,  " s" },
    { WHITE_GOLD,    " g" },
    { WHITE_BISHOP,  " b" },
    { WHITE_ROOK,    " r" },
    { WHITE_KING,    " k" },
    { WHITE_PAWN_PROMOTE,   "+p" },
    { WHITE_LANCE_PROMOTE,  "+l" },
    { WHITE_KNIGHT_PROMOTE, "+n" },
    { WHITE_SILVER_PROMOTE, "+s" },
    { WHITE_BISHOP_PROMOTE, "+b" },
    { WHITE_ROOK_PROMOTE,   "+r" }
};